### PR TITLE
v2.0.0 

### PR DESCRIPTION
**Pull request by johnnycoinbase**
- separate packages for v1 and v2 classes

### CODE REVIEW

**Comment by aianus** [comment]
We can remove the v1 classes entirely from master/v2.

As long as v2 is in a separate package from v1, consumers who need both versions for some reason can install them side-by-side.

**Comment by ankurbn** [comment]
Are there any API's that are implemented as v1, but not as v2?

**Comment by johnnycoinbase** [comment]
Yeah, all v1 APIs are still present. They're being marked as deprecated while v2 is being rolled out.

**Comment by ankurbn** [comment]
Lets stick with the current approach of having V1 and V2 together.

**Pull request merged**
